/**
 * Per-provider `KIMI_SHARE_DIR` management for SmartCrab.
 *
 * The Kimi Agent SDK (used by `@seher-ts/sdk` for both `kimi` and `openai`
 * provider kinds) spawns the `kimi` CLI as a subprocess. The CLI selects its
 * upstream LLM endpoint from `<KIMI_SHARE_DIR>/config.toml`. Env vars only
 * override `api_key` / `base_url` *for an already-configured provider type* —
 * they cannot switch the active provider type from `kimi` to `openai_legacy`.
 *
 * To support both `kimi` and `openai` (OpenAI API-compatible) provider kinds
 * without touching the user's own `~/.kimi/config.toml`, SmartCrab gives each
 * provider its own share directory and writes a generated `config.toml`.
 *
 *   ~/Library/Application Support/SmartCrab/kimi-share/<providerId>/config.toml
 *
 * Override the root via `SMARTCRAB_KIMI_SHARE_ROOT` (mainly for tests).
 */

import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/** SmartCrab kinds whose runtime is the Kimi CLI. */
export type KimiBackedKind = "kimi" | "openai";

const KIND_TO_KIMI_TYPE: Record<KimiBackedKind, "kimi" | "openai_legacy"> = {
  kimi: "kimi",
  openai: "openai_legacy",
};

const KIND_TO_DEFAULT_BASE_URL: Record<KimiBackedKind, string> = {
  kimi: "https://api.kimi.com/coding/v1",
  openai: "https://api.openai.com/v1",
};

export function isKimiBackedKind(kind: string): kind is KimiBackedKind {
  return kind === "kimi" || kind === "openai";
}

/**
 * Restrict providerId to characters safe both in TOML bare keys and on disk.
 * `.` is intentionally excluded so a `providers.foo.bar` table header is not
 * misparsed as a nested table; an empty result falls back to a placeholder
 * so callers never `join(root, "")` (which collapses to the root itself).
 */
function sanitizeProviderId(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_-]/g, "_");
  return cleaned === "" ? "unnamed" : cleaned;
}

export function defaultKimiShareRoot(): string {
  return (
    process.env.SMARTCRAB_KIMI_SHARE_ROOT ??
    join(homedir(), "Library", "Application Support", "SmartCrab", "kimi-share")
  );
}

export function kimiShareDirFor(providerId: string): string {
  return join(defaultKimiShareRoot(), sanitizeProviderId(providerId));
}

/**
 * Render a minimal Kimi `config.toml` selecting the given provider type as
 * the active provider. `api_key` is left empty so the user's `envOverrides`
 * (`KIMI_API_KEY` / `OPENAI_API_KEY`) decide the credential at runtime.
 */
function renderKimiConfigToml(args: {
  safeId: string;
  kind: KimiBackedKind;
}): string {
  const banner =
    "# Generated by SmartCrab from the in-app Settings tab. Do not edit by hand —\n" +
    "# changes will be overwritten on the next `settings.app-save`.\n\n";
  return (
    banner +
    `provider = "${args.safeId}"\n\n` +
    `[providers.${args.safeId}]\n` +
    `type = "${KIND_TO_KIMI_TYPE[args.kind]}"\n` +
    `base_url = "${KIND_TO_DEFAULT_BASE_URL[args.kind]}"\n` +
    `api_key = ""\n`
  );
}

/**
 * Idempotently write `<shareDir>/config.toml`. Skips the write when the file
 * already matches, and uses tmp+rename for atomicity so a concurrently
 * running `kimi` CLI never sees a partial file. Returns the share dir path.
 */
export function writeKimiShare(args: {
  providerId: string;
  kind: KimiBackedKind;
}): string {
  const safeId = sanitizeProviderId(args.providerId);
  const dir = join(defaultKimiShareRoot(), safeId);
  const target = join(dir, "config.toml");
  const content = renderKimiConfigToml({ safeId, kind: args.kind });

  try {
    if (readFileSync(target, "utf8") === content) return dir;
  } catch {
    // Missing or unreadable — fall through to write.
  }

  mkdirSync(dir, { recursive: true });
  const tmp = `${target}.tmp`;
  writeFileSync(tmp, content, "utf8");
  renameSync(tmp, target);
  return dir;
}

export function removeKimiShare(providerId: string): void {
  const dir = kimiShareDirFor(providerId);
  rmSync(dir, { recursive: true, force: true });
}
