name: sakoku

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sakoku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run sakoku
        uses: smartcrabai/sakoku@695e06ebbdf9c36c3f0bb72feb8b4eb2cdd5b885 # v0.2.4
